### PR TITLE
Fix compilation on 32-bit

### LINKED ISSUE #534: support arm32/arm64 platform
### The problem

Info: source code build on raspberry Pi 4 Ubuntu 20.04.1 
OS: Linux  5.4.0-1021-raspi #24-Ubuntu SMP PREEMPT Mon Oct 5 10:02:34 UTC 2020 armv7l armv7l armv7l GNU/Linux
cc c++ version: gcc version 9.3.0

Compile Error: 

Temporary build directory is /tmp/SetReplace/Build

CreateLibrary::cmperr: Compile error: /home/chenfeng/SetReplace-7/libSetReplace/SetReplace.cpp:196:42: error: no match for call to ‘(const SetReplace::putEvents(const std::vector<SetReplace::Event>&, WolframLibraryData)::<lambda(const std::vector<int>&)>) (const std::vector<long long int>&)’

CreateLibrary::cmperr: Compile error: /home/chenfeng/SetReplace-7/libSetReplace/SetReplace.cpp:201:43: error: no match for call to ‘(const SetReplace::putEvents(const std::vector<SetReplace::Event>&, WolframLibraryData)::<lambda(const std::vector<int>&)>) (const std::vector<long long int>&)’

buildLibSetReplace::fail: Compilation failed. Paclet will be created without low level implementation.
Build failed.

### Expected behavior

want to run WolframModel on **raspberry pi 4 armv7l** 

### Version
```wl
In[] := SystemInformation["Small"]
```
```
Out[1]= {Kernel ->

>     {SystemID -> Linux-ARM, ReleaseID -> 12.1.1.0 (0, 2020081801),

>      CreationDate ->

>       DateObject[{2020, 8, 18, 19, 17, 15}, Instant, Gregorian, 0.]},

>    FrontEnd -> Missing[NotActive]}
```

```
SetReplace branch: v0.3.92
```

### PR DESCRIPTION
**Pull request by aokellermann**
## Changes
* Fixes #534

---
This change is [Reviewable](https://reviewable.io/reviews/maxitg/setreplace/538)

### CODE REVIEW

**Review by maxitg — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/538)* status: :shipit: complete! all files reviewed, all discussions resolved
